### ISSUE TITLE
FRONTEND: Page Layout Beautification and unification

### ISSUE THREAD

**Issue by Clxiu** [Trust-Indicator/Trust-Indicator#31]
## Description
Beautify and unify page layout. 

## Close Criteria
- Unify navigation bar style and content. 
- Unify footer style. 
- Reduce duplication in CSS and JS files. 
For following pages: 
- [x] feedback.html
- [x] index.html
- [x] userprofile.html
- [x] gallery.html
- [x] upload.html
- [x] whatwedo.html
- [x] feedback.html
- [x] etc ..

**Comment by Clxiu** [comment]
Finish unifying navigation bar style and content, and footer style for existing pages.

**Comment by Clxiu** [comment]
Changed sliders in index.html and added logos to all pages.

**Comment by Clxiu** [comment]
Fixed navigation bar display error for smaller screen size.

**Comment by tonypioneer** [comment]
Close as completed.
