### ISSUE TITLE
FRONTEND: What We Do page

### ISSUE THREAD

**Issue by Clxiu** [Trust-Indicator/Trust-Indicator#32]
## Description
Add a What We Do page to the website.

## Close Criteria: 
- [x] Develop a webpage.
- [x] Include Mission statement.
- [x] Include Recognition method
- [x] Include an explanation of credibility signals.
- [x] Other explanation.

**Comment by Clxiu** [comment]
Finished webpage design. Add placeholder for statements.

**Comment by Clxiu** [comment]
Add recognition method explanation.

**Comment by tonypioneer** [comment]
Close as completed.
